### ISSUE TITLE
`pip install` into new virtualenv does not include thrift dependencies

### ISSUE THREAD

**Issue by acompa** [dropbox/PyHive#129]
Just tried installing PyHive into a new virtualenv, but I'm seeing some issues with its dependencies on thrift:

```
~ mkvirtualenv pyhive-test
New python executable in /Users/alexcompanioni/.virtualenvs/pyhive-test/bin/python2.7
Not overwriting existing python script /Users/alexcompanioni/.virtualenvs/pyhive-test/bin/python (you must use /Users/alexcompanioni/.virtualenvs/pyhive-test/bin/python2.7)
Installing setuptools, pip, wheel...done.

(pyhive-test) ~ pip install "pyhive[hive]"
Requirement already satisfied: pyhive[hive] in ./.virtualenvs/pyhive-test/lib/python2.7/site-packages
  Ignoring thrift: markers 'extra == "Hive"' don't match your environment
  Ignoring thrift-sasl: markers 'extra == "Hive"' don't match your environment
  Ignoring sasl: markers 'extra == "Hive"' don't match your environment
Requirement already satisfied: future in ./.virtualenvs/pyhive-test/lib/python2.7/site-packages (from pyhive[hive])
```

Then, after this happens:

```
(pyhive-test) ~ python
Python 2.7.13 (default, Dec 18 2016, 07:03:39)
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from pyhive import hive
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/alexcompanioni/.virtualenvs/pyhive-test/lib/python2.7/site-packages/pyhive/hive.py", line 10, in <module>
    from TCLIService import TCLIService
  File "/Users/alexcompanioni/.virtualenvs/pyhive-test/lib/python2.7/site-packages/TCLIService/TCLIService.py", line 9, in <module>
    from thrift.Thrift import TType, TMessageType, TFrozenDict, TException, TApplicationException
ImportError: No module named thrift.Thrift
```

I can reproduce this if I also try to create the virtualenv against my local Python 3 installation.

**Comment by polvoazul** [comment]
I can reproduce this.

**Comment by jingw** [comment]
Thanks for the report. For whatever reason, this doesn't happen with a clean ~/.pip/cache, but a second attempt reproduces. It looks like the extras are sometimes handled case sensitive, but the pip cli lowercases whatever's passed in. (maybe a bug in pip)

I'll fix.

**Comment by acompa** [comment]
Thanks for this fix, @jingw!
