### ISSUE TITLE
Cannot connect to HiveServer2 Interactive instance / LLAP

### ISSUE THREAD

**Issue by mdeguzis** [dropbox/PyHive#142]
```
 69 if args.hive_interactive:
 70     HOST = 'lldaphost.host.com'
 71 elif not args.host:
 72     HOST = 'hiveserver2host.host.com'
 73
 74 if args.hive_interactive:
 75     PORT = 10500
 76 elif not args.port:
 77     PORT = 10000

 94 try:
 95     logging.info("Establishing Hive connection...")
 96     # Do not use the full principal for  hive, just "hive"
 97     conn = hive.Connection(host=HOST, port=PORT, auth="KERBEROS", \
 98     database=databse,kerberos_service_name="hive")
 99     #except TTransport.TTransportException:
100 except:
101     raise
```

Error:
```
Traceback (most recent call last):
  File "/home/user/python-hive/buildout/bin/python", line 38, in <module>
    exec(compile(__file__f.read(), __file__, "exec"))
  File "/home/mtdeguzis/python-hive/pyhive.py", line 98, in <module>
    database=databse,kerberos_service_name="hive")
  File "/home/user/python-hive/buildout/src/pyhive/pyhive/hive.py", line 131, in __init__
    self._transport.open()
  File "/home/user/python-hive/buildout/eggs/thrift_sasl-0.2.1-py2.7.egg/thrift_sasl/__init__.py", line 80, in open
    status, payload = self._recv_sasl_message()
  File "/home/user/python-hive/buildout/eggs/thrift_sasl-0.2.1-py2.7.egg/thrift_sasl/__init__.py", line 101, in _recv_sasl_message
    payload = read_all_compat(self._trans, length)
  File "/home/user/python-hive/buildout/eggs/thrift_sasl-0.2.1-py2.7.egg/thrift_sasl/six.py", line 31, in <lambda>
    read_all_compat = lambda trans, sz: trans.readAll(sz)
  File "/home/user/python-hive/buildout/eggs/thrift-0.10.0-py2.7-linux-x86_64.egg/thrift/transport/TTransport.py", line 60, in readAll
    chunk = self.read(sz - have)
  File "/home/user/python-hive/buildout/eggs/thrift-0.10.0-py2.7-linux-x86_64.egg/thrift/transport/TSocket.py", line 132, in read
    message='TSocket read 0 bytes')
thrift.transport.TTransport.TTransportException: TSocket read 0 bytes
```

Is there an different approach for this or is Hive Interactive not supported?

**Comment by mdeguzis** [comment]
I'll look over https://www.python.org/dev/peps/pep-0249/ as well.

**Comment by mdeguzis** [comment]
I believe this is my fault, found out we do not have a kerberized instance on the host. Sorry.
