### ISSUE TITLE
Cannot use LDAP: Password / LDAP auth not picked up?

### ISSUE THREAD

**Issue by mdeguzis** [dropbox/PyHive#143]
I am trying to use LDAP auth, but I can't see to get the code to accept it:

Input vars:
```
AUTH = LDAP
PRINCIPAL = ""
HOST = <my_host>
port = <my_port>
```

```
conn = hive.Connection(host=HOST, port=PORT, auth=AUTH, \
database=databse,kerberos_service_name=PRINCIPAL)
```

I added some output right above this check (which should be logged anyway for debugging, it is not):

```
print "password: " + str(password)
print "auth: " + str(auth)

if (password is not None) != (auth == 'LDAP'):
 raise ValueError("password should be set if and only if in LDAP mode")
```

I get this raise even when the password value is "None" and auth value is "LDAP".

It appears this logic check should be:

```
if (password is not None) and (auth != "LDAP"):
```

Agreed?

**Comment by mdeguzis** [comment]
misunderstanding of code, passed in appropriate username, password values.

**Comment by mtdeguzis** [comment]
Still having this issue, seems like I can't get a connection:

```
>>> cursor = hive.Connection(host=host, port=port, auth=auth, username=username, password=password, database=database, kerberos_service_name=principal).cursor()
Please enter your password:
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/home/mtdeguzis/python-hive/buildout-testing/src/pyhive/pyhive/hive.py", line 131, in __init__
    self._transport.open()
  File "/home/mtdeguzis/python-hive/buildout-testing/eggs/thrift_sasl-0.2.1-py2.7.egg/thrift_sasl/__init__.py", line 80, in open
    status, payload = self._recv_sasl_message()
  File "/home/mtdeguzis/python-hive/buildout-testing/eggs/thrift_sasl-0.2.1-py2.7.egg/thrift_sasl/__init__.py", line 101, in _recv_sasl_message
    payload = read_all_compat(self._trans, length)
  File "/home/mtdeguzis/python-hive/buildout-testing/eggs/thrift_sasl-0.2.1-py2.7.egg/thrift_sasl/six.py", line 31, in <lambda>
    read_all_compat = lambda trans, sz: trans.readAll(sz)
  File "/home/mtdeguzis/python-hive/buildout-testing/eggs/thrift-0.10.0-py2.7-linux-x86_64.egg/thrift/transport/TTransport.py", line 60, in readAll
    chunk = self.read(sz - have)
  File "/home/mtdeguzis/python-hive/buildout-testing/eggs/thrift-0.10.0-py2.7-linux-x86_64.egg/thrift/transport/TSocket.py", line 132, in read
    message='TSocket read 0 bytes')
TTransportException: TSocket read 0 bytes
```

**Comment by mtdeguzis** [comment]
From hiveserver2.log:
```
tail -f hiveserver2.log
        at sun.security.ssl.InputRecord.read(InputRecord.java:527)
        at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:973)
        at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1375)
        at sun.security.ssl.SSLSocketImpl.readDataRecord(SSLSocketImpl.java:928)
        at sun.security.ssl.AppInputStream.read(AppInputStream.java:105)
        at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
        at java.io.BufferedInputStream.read1(BufferedInputStream.java:286)
        at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
        at org.apache.thrift.transport.TIOStreamTransport.read(TIOStreamTransport.java:127)
        ... 10 more
2017-07-31 17:29:55,608 ERROR [HiveServer2-Handler-Pool: Thread-234956]: server.TThreadPoolServer (TThreadPoolServer.java:run(297)) - Error occurred during processing of message.
java.lang.RuntimeException: org.apache.thrift.transport.TTransportException: javax.net.ssl.SSLException: Unrecognized SSL message, plaintext connection?
        at org.apache.thrift.transport.TSaslServerTransport$Factory.getTransport(TSaslServerTransport.java:219)
        at org.apache.thrift.server.TThreadPoolServer$WorkerProcess.run(TThreadPoolServer.java:269)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.thrift.transport.TTransportException: javax.net.ssl.SSLException: Unrecognized SSL message, plaintext connection?
        at org.apache.thrift.transport.TIOStreamTransport.read(TIOStreamTransport.java:129)
        at org.apache.thrift.transport.TTransport.readAll(TTransport.java:86)
        at org.apache.thrift.transport.TSaslTransport.receiveSaslMessage(TSaslTransport.java:178)
        at org.apache.thrift.transport.TSaslServerTransport.handleSaslStartMessage(TSaslServerTransport.java:125)
        at org.apache.thrift.transport.TSaslTransport.open(TSaslTransport.java:271)
        at org.apache.thrift.transport.TSaslServerTransport.open(TSaslServerTransport.java:41)
        at org.apache.thrift.transport.TSaslServerTransport$Factory.getTransport(TSaslServerTransport.java:216)
        ... 4 more
Caused by: javax.net.ssl.SSLException: Unrecognized SSL message, plaintext connection?
        at sun.security.ssl.InputRecord.handleUnknownRecord(InputRecord.java:710)
        at sun.security.ssl.InputRecord.read(InputRecord.java:527)
        at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:973)
        at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1375)
        at sun.security.ssl.SSLSocketImpl.readDataRecord(SSLSocketImpl.java:928)
        at sun.security.ssl.AppInputStream.read(AppInputStream.java:105)
        at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
        at java.io.BufferedInputStream.read1(BufferedInputStream.java:286)
        at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
        at org.apache.thrift.transport.TIOStreamTransport.read(TIOStreamTransport.java:127)
        ... 10 more
```

**Comment by shaunjl** [comment]
@mdeguzis I am having the same issue. Bump.

**Comment by mtdeguzis** [comment]
Any update on this?

**Comment by devinstevenson** [comment]
@mtdeguzis It looks like you are submitting as a string `'None'` for kerberos_service_name. LDAP and KERBEROS are mutually exclusive AFAIK. If using LDAP, don't provide any kerberos parameters.

**Comment by mdeguzis** [comment]
I have this in my module code:

```
 41         elif AUTH == "LDAP":
 42             cursor = hive.Connection(host=HOST, port=PORT, auth=AUTH, \
 43             username=USERNAME, password=PASSWORD, database=database).cursor()
```

No keberos_service_name in my current code. I am not sure where ssl is coming into play. Our cluster can't accept the PLAIN auth type that is being sent.

**Comment by mtdeguzis** [comment]
If I try to use LDAP for auth I get this:

```
 41         elif AUTH == "LDAP":
 42             cursor = hive.Connection(host=HOST, port=PORT, auth=AUTH, \
 43             username=USERNAME, password=PASSWORD, database=database).cursor()

Traceback (most recent call last):
  File "hiveserver2-service-check.py", line 276, in <module>
    main()
  File "hiveserver2-service-check.py", line 269, in main
    check.main(verbose=args.verbose)
  File "/home/icinga/.local/share/virtualenvs/hiveserver2-service-check-wPnGv84d/lib/python2.7/site-packages/nagiosplugin/check.py", line 120, in main
    runtime.execute(self, verbose, timeout)
  File "/home/icinga/.local/share/virtualenvs/hiveserver2-service-check-wPnGv84d/lib/python2.7/site-packages/nagiosplugin/runtime.py", line 130, in execute
    self.run(check)
  File "/home/icinga/.local/share/virtualenvs/hiveserver2-service-check-wPnGv84d/lib/python2.7/site-packages/nagiosplugin/runtime.py", line 117, in run
    check()
  File "/home/icinga/.local/share/virtualenvs/hiveserver2-service-check-wPnGv84d/lib/python2.7/site-packages/nagiosplugin/check.py", line 105, in __call__
    self._evaluate_resource(resource)
  File "/home/icinga/.local/share/virtualenvs/hiveserver2-service-check-wPnGv84d/lib/python2.7/site-packages/nagiosplugin/check.py", line 72, in _evaluate_resource
    metrics = resource.probe()
  File "hiveserver2-service-check.py", line 56, in probe
    cursor = self.get_cursor()
  File "hiveserver2-service-check.py", line 49, in get_cursor
    self.PASSWORD, self.PORT, self.PRINCIPAL, self.USERNAME)
  File "/opt/icinga-plugins/hiveserver2-service-check/python-opstools/opstools/hdppyhive.py", line 43, in hive_connection
    username=USERNAME, password=PASSWORD, database=database).cursor()
  File "/home/icinga/.local/share/virtualenvs/hiveserver2-service-check-wPnGv84d/lib/python2.7/site-packages/pyhive/hive.py", line 162, in __init__
    self._transport.open()
  File "/home/icinga/.local/share/virtualenvs/hiveserver2-service-check-wPnGv84d/lib/python2.7/site-packages/thrift_sasl/__init__.py", line 90, in open
    message=("Bad status: %d (%s)" % (status, payload)))
thrift.transport.TTransport.TTransportException: Bad status: 3 (Unsupported mechanism type PLAIN)
```

**Comment by mtdeguzis** [comment]
I did see https://github.com/dropbox/PyHive/pull/104 for SSL support, but the code has diverged too much for any testing on such a PR. I know several folks cannot use SASL and have to use SSL. Any plans for this??

**Comment by mtdeguzis** [comment]
I saw #203, is this related at all? Can session information be passed in this way?

**Comment by mtdeguzis** [comment]
It really seems you just need this:

```
import thrift.transport.TSSLSocket
socket = thrift.transport.TSSLSocket.TSSLSocket(host, port, ca_certs = 'some_cert')
```

I just get a failure to verify the cert:
```
SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:579)
```

... which is probably something else. With such a simple routing, it would seem this is ripe for some upstream dev testing with a cert that works.
