### ISSUE TITLE
Query hangs

### ISSUE THREAD

**Issue by mrfuxi** [dropbox/PyHive#145]
For some queries, pyhive hangs after hive execution is over. I tried constructing engine in all ways mentioned in docs.
Only when I use it in async mode it actually works for all queries, but then I can not use it with SqlAlchemy.

Some of my debugging lead me to the conclusion it has something with trying to use data generated from multiple `WITH` selects.

All queries run just fine from HUE on Hive

The moment I kill the program with "CMD-C" it spits out traceback like that:

```
Traceback (most recent call last):
  File "/home/me/.virtualenvs/project/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1405, in _handle_dbapi_exception
    util.reraise(*exc_info)
  File "/home/me/.virtualenvs/project/lib/python3.5/site-packages/sqlalchemy/util/compat.py", line 187, in reraise
    raise value
  File "/home/me/.virtualenvs/project/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1182, in _execute_context
    context)
  File "/home/me/.virtualenvs/project/lib/python3.5/site-packages/sqlalchemy/engine/default.py", line 470, in do_execute
    cursor.execute(statement, parameters)
  File "/home/me/.virtualenvs/project/lib/python3.5/site-packages/pyhive/hive.py", line 267, in execute
    response = self._connection.client.ExecuteStatement(req)
  File "/home/me/.virtualenvs/project/lib/python3.5/site-packages/TCLIService/TCLIService.py", line 280, in ExecuteStatement
    return self.recv_ExecuteStatement()
  File "/home/me/.virtualenvs/project/lib/python3.5/site-packages/TCLIService/TCLIService.py", line 292, in recv_ExecuteStatement
    (fname, mtype, rseqid) = iprot.readMessageBegin()
  File "/home/me/.virtualenvs/project/lib/python3.5/site-packages/thrift/protocol/TBinaryProtocol.py", line 134, in readMessageBegin
    sz = self.readI32()
  File "/home/me/.virtualenvs/project/lib/python3.5/site-packages/thrift/protocol/TBinaryProtocol.py", line 217, in readI32
    buff = self.trans.readAll(4)
  File "/home/me/.virtualenvs/project/lib/python3.5/site-packages/thrift/transport/TTransport.py", line 60, in readAll
    chunk = self.read(sz - have)
  File "/home/me/.virtualenvs/project/lib/python3.5/site-packages/thrift_sasl/__init__.py", line 166, in read
    self._read_frame()
  File "/home/me/.virtualenvs/project/lib/python3.5/site-packages/thrift_sasl/__init__.py", line 170, in _read_frame
    header = self._trans.readAll(4)
  File "/home/me/.virtualenvs/project/lib/python3.5/site-packages/thrift/transport/TTransport.py", line 60, in readAll
    chunk = self.read(sz - have)
  File "/home/me/.virtualenvs/project/lib/python3.5/site-packages/thrift/transport/TSocket.py", line 118, in read
    buff = self.handle.recv(sz)
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/me/app.py"
    (row.id, row) for row in engine.execute(sql, sql_args)
  File "/home/me/.virtualenvs/project/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 2064, in execute
    return connection.execute(statement, *multiparams, **params)
  File "/home/me/.virtualenvs/project/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 939, in execute
    return self._execute_text(object, multiparams, params)
  File "/home/me/.virtualenvs/project/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1097, in _execute_text
    statement, parameters
  File "/home/me/.virtualenvs/project/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1189, in _execute_context
    context)
  File "/home/me/.virtualenvs/project/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1415, in _handle_dbapi_exception
    self.invalidate(e)
  File "/home/me/.virtualenvs/project/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 536, in invalidate
    self._root.__connection.invalidate(exception)
  File "/home/me/.virtualenvs/project/lib/python3.5/site-packages/sqlalchemy/pool.py", line 914, in invalidate
    self._connection_record.invalidate(e=e, soft=soft)
  File "/home/me/.virtualenvs/project/lib/python3.5/site-packages/sqlalchemy/pool.py", line 600, in invalidate
    self.__close()
  File "/home/me/.virtualenvs/project/lib/python3.5/site-packages/sqlalchemy/pool.py", line 640, in __close
    self.__pool._close_connection(self.connection)
  File "/home/me/.virtualenvs/project/lib/python3.5/site-packages/sqlalchemy/pool.py", line 300, in _close_connection
    self._dialect.do_close(connection)
  File "/home/me/.virtualenvs/project/lib/python3.5/site-packages/sqlalchemy/engine/default.py", line 446, in do_close
    dbapi_connection.close()
  File "/home/me/.virtualenvs/project/lib/python3.5/site-packages/pyhive/hive.py", line 151, in close
    response = self._client.CloseSession(req)
  File "/home/me/.virtualenvs/project/lib/python3.5/site-packages/TCLIService/TCLIService.py", line 218, in CloseSession
    return self.recv_CloseSession()
  File "/home/me/.virtualenvs/project/lib/python3.5/site-packages/TCLIService/TCLIService.py", line 230, in recv_CloseSession
    (fname, mtype, rseqid) = iprot.readMessageBegin()
  File "/home/me/.virtualenvs/project/lib/python3.5/site-packages/thrift/protocol/TBinaryProtocol.py", line 134, in readMessageBegin
    sz = self.readI32()
  File "/home/me/.virtualenvs/project/lib/python3.5/site-packages/thrift/protocol/TBinaryProtocol.py", line 217, in readI32
    buff = self.trans.readAll(4)
  File "/home/me/.virtualenvs/project/lib/python3.5/site-packages/thrift/transport/TTransport.py", line 60, in readAll
    chunk = self.read(sz - have)
  File "/home/me/.virtualenvs/project/lib/python3.5/site-packages/thrift_sasl/__init__.py", line 166, in read
    self._read_frame()
  File "/home/me/.virtualenvs/project/lib/python3.5/site-packages/thrift_sasl/__init__.py", line 170, in _read_frame
    header = self._trans.readAll(4)
  File "/home/me/.virtualenvs/project/lib/python3.5/site-packages/thrift/transport/TTransport.py", line 60, in readAll
    chunk = self.read(sz - have)
  File "/home/me/.virtualenvs/project/lib/python3.5/site-packages/thrift/transport/TSocket.py", line 118, in read
    buff = self.handle.recv(sz)
```

**Comment by mrfuxi** [comment]
After further examination, it could be a timeout problem on Hive end

**Comment by jingw** [comment]
It might help to repro against a boring Cloudera CDH setup (https://github.com/dropbox/PyHive/wiki#local-testing). If it's not possible to repro against that setup, it might help to diff your Hive config against the boring config, which may point to some issue in how you're configuring Hive or this client.

I can't do much with the information provided, sorry. All I can say is that I don't have this problem in the Travis test environment or in my production environment :)

**Comment by mrfuxi** [comment]
Thanks for the link, look like it's a problem with some setup.
Would be nice if there would be an exception raised rather than the whole app frozen completely.
