### ISSUE TITLE
connection hive server2 thrift.Thrift.TApplicationException: Invalid method name: 'OpenSession' 

### ISSUE THREAD

**Issue by PingGao89** [dropbox/PyHive#201]
hi
   connection hive server2 Throw thrift.Thrift.TApplicationException: Invalid method name: 'OpenSession',Use beeline client to connect successfully

python version 3.6
hive-0.13.1-cdh5.2.6
PyHive (0.5.1)
thrift (0.11.0)
thrift-sasl (0.3.0)
sasl (0.2.1)

Exception:
  Traceback (most recent call last):
  File "test_hive.py", line 3, in <module>
    cursor = hive.connect(host="192.168.104.179", port=30000,database="db_new",auth="NOSASL").cursor()
  File "/usr/local/lib/python3.6/site-packages/PyHive-0.5.1-py3.6.egg/pyhive/hive.py", line 64, in connect
  File "/usr/local/lib/python3.6/site-packages/PyHive-0.5.1-py3.6.egg/pyhive/hive.py", line 168, in __init__
  File "/usr/local/lib/python3.6/site-packages/PyHive-0.5.1-py3.6.egg/TCLIService/TCLIService.py", line 187, in OpenSession
  File "/usr/local/lib/python3.6/site-packages/PyHive-0.5.1-py3.6.egg/TCLIService/TCLIService.py", line 204, in recv_OpenSession
thrift.Thrift.TApplicationException: Invalid method name: 'OpenSession'

**Comment by PingGao89** [comment]
This is caused by hive server2 not adding --hiveconf hive.server2.authentication=NOSASL startup parameter
