### ISSUE TITLE
[BUG] PyHive SQLAlchemy reflection problem

### ISSUE THREAD

**Issue by yiakwy** [dropbox/PyHive#238]
> NotImplementedError: Operator 'getitem' ...
 
After

```python
Base = declarative_base()
Base.query = session.query_property()
meta = MetaData(bind=engine)

class XX(Base):
    __tablename__ "test"
    __table__ = meta.tables(__tablename__)
    __mapper_args__ = [__table__.c.id, ]
```

, an error was caused for reason 'NotImplementedError: Operator 'getitem' xx"

**Comment by yiakwy** [comment]
Later I changed the methods used for reflection:

```pyhton
def create_conn():
    return hive.Connection(**config)
# sqlalchemy engine instance
engine = create_engine("hive://", creator=create_conn)
SessOption = {
    "autocommit": False,
    "autoflush": False,
    "bind": engine 
}
session = scoped_session(sessionmaker(**SessOption))
# for more information see hsettp://docs.sqlalchemy.org/en/latest/orm/extensions/automap.html
# the most recent method of using SQLalchemy is through the declarative extension of that. 
Base = declarative_base()
Base.query = session.query_property()
meta = MetaData(bind=engine)
# meta = MetaData()
# meta.reflect(bind=engine)

def init_hivedb(*ModelModules):
    HiveModelLoader().load(*ModelModules)
    Base.metadata.create_all(bind=engine)

@app.teardown_appcontext
def shutdown_session(exception=None):
    session.remove()

ImportModule = __import__ 

class HiveModelLoader:

    def __init__(self):
        self.defaultModule = []
        self.modules = {}

    def load(*ModelModules):
        for mod in ModelModules:
            try:
                module = ImportModule("models.backends.hive.model.%s" % mod)
                self.modules[mod] = module
            except ImportError:
                print(chalk.red("<models.backends.hive.model.%s> does not exist" % mod))


class ConfluenceActivity(Base):
    __tablename__ = 'XX'
    __table__ = Table(__tablename__, meta, autoload=True)# meta.tables['d_i_confluence_spaces_comment']
```

I FOUND

```txt
File "/Users/lei.wang1/VirtualEnv/Py3/lib/python3.6/site-packages/thrift/transport/TSocket.py", line 132, in read
    message='TSocket read 0 bytes')
thrift.transport.TTransport.TTransportException: TSocket read 0 bytes

```

By diving into the codes:

```python
(Pdb) b /Users/lei.wang1/VirtualEnv/Py3/lib/python3.6/site-packages/pyhive/hive.py:209
Breakpoint 1 at /Users/lei.wang1/VirtualEnv/Py3/lib/python3.6/site-packages/pyhive/hive.py:209
(Pdb) c
Traceback (most recent call last):
  File "/Users/lei.wang1/VirtualEnv/Py3/lib/python3.6/site-packages/pyhive/hive.py", line 198, in __init__
    response = self._client.OpenSession(open_session_req)
  File "/Users/lei.wang1/VirtualEnv/Py3/lib/python3.6/site-packages/TCLIService/TCLIService.py", line 187, in OpenSession
    return self.recv_OpenSession()
  File "/Users/lei.wang1/VirtualEnv/Py3/lib/python3.6/site-packages/TCLIService/TCLIService.py", line 199, in recv_OpenSession
    (fname, mtype, rseqid) = iprot.readMessageBegin()
  File "/Users/lei.wang1/VirtualEnv/Py3/lib/python3.6/site-packages/thrift/protocol/TBinaryProtocol.py", line 148, in readMessageBegin
    name = self.trans.readAll(sz)
  File "/Users/lei.wang1/VirtualEnv/Py3/lib/python3.6/site-packages/thrift/transport/TTransport.py", line 60, in readAll
    chunk = self.read(sz - have)
  File "/Users/lei.wang1/VirtualEnv/Py3/lib/python3.6/site-packages/thrift/transport/TTransport.py", line 161, in read
    self.__rbuf = BufferIO(self.__trans.read(max(sz, self.__rbuf_size)))
  File "/Users/lei.wang1/VirtualEnv/Py3/lib/python3.6/site-packages/thrift/transport/TSocket.py", line 132, in read
    message='TSocket read 0 bytes')
thrift.transport.TTransport.TTransportException: TSocket read 0 bytes
> /Users/lei.wang1/VirtualEnv/Py3/lib/python3.6/site-packages/pyhive/hive.py(209)__init__()
-> self._transport.close()

```

There must be some problems in your implementation of Connect. I can confirm that *create_conn* standalone works fine which can create a connectiont to hive server. But it does not work in reflection context.

@graham

**Comment by yiakwy** [comment]
@jingw @ptallada

**Comment by yiakwy** [comment]
@gsilk Thanks for your attention! I am getting familiar with the source code of PyHive. I will try my best to find a solution to that problem. I am appreciated if you can help me along the way. ~ ~
