### ISSUE TITLE
Hive Query Timeout - [Errno 110] Connection timed out 

### ISSUE THREAD

**Issue by mahendra-jadav** [dropbox/PyHive#248]
I am running Hive queries from Python using PyHive. One of the query is taking around 12-15 minutes to complete. I could see it completed on Hadoop ResourceManager UI, however I am seeing bellow timeout error on Python

```
Error:Traceback (most recent call last): File "/home/mrjadav/python/thunderbolt.py", line 704, in main() File "/home/mrjadav/python/thunderbolt.py", line 662, in main getColoLatency() File "/home/mrjadav/python/thunderbolt.py", line 582, in getColoLatency dataSet = saveHqlResultToXls(queryString=queryString, caption='Colo Latency Breakdown', configuration=g_hive_config_heavy) File "/home/mrjadav/python/thunderbolt.py", line 636, in saveHqlResultToXls dataSet=cursor.fetchall() File "/home/y/lib/python2.7/site-packages/pyhive/common.py", line 136, in fetchall return list(iter(self.fetchone, None)) File "/home/y/lib/python2.7/site-packages/pyhive/common.py", line 105, in fetchone self._fetch_while(lambda: not self._data and self._state != self._STATE_FINISHED) File "/home/y/lib/python2.7/site-packages/pyhive/common.py", line 45, in _fetch_while self._fetch_more() File "/home/y/lib/python2.7/site-packages/pyhive/hive.py", line 386, in _fetch_more response = self._connection.client.FetchResults(req) File "/home/y/lib/python2.7/site-packages/TCLIService/TCLIService.py", line 714, in FetchResults return self.recv_FetchResults() File "/home/y/lib/python2.7/site-packages/TCLIService/TCLIService.py", line 726, in recv_FetchResults (fname, mtype, rseqid) = iprot.readMessageBegin() File "/home/y/lib/python2.7/site-packages/thrift/protocol/TBinaryProtocol.py", line 134, in readMessageBegin sz = self.readI32() File "/home/y/lib/python2.7/site-packages/thrift/protocol/TBinaryProtocol.py", line 217, in readI32 buff = self.trans.readAll(4) File "/home/y/lib/python2.7/site-packages/thrift/transport/TTransport.py", line 60, in readAll chunk = self.read(sz - have) File "/home/y/lib/python2.7/site-packages/thrift_sasl/__init__.py", line 166, in read self._read_frame() File "/home/y/lib/python2.7/site-packages/thrift_sasl/__init__.py", line 170, in _read_frame header = self._trans.readAll(4) File "/home/y/lib/python2.7/site-packages/thrift/transport/TTransport.py", line 60, in readAll chunk = self.read(sz - have) File "/home/y/lib/python2.7/site-packages/thrift/transport/TSocket.py", line 117, in read buff = self.handle.recv(sz) error: [Errno 110] Connection timed out 
```

**Comment by meorilehr** [comment]
we're experiencing a similar issue with long lasting connections when we are trying to close the connections when done executing the queries with this stack trace:

```
File "/usr/local/lib/python3.6/site-packages/pyhive/hive.py", line 183, in close
response = self._client.CloseSession(req)
File "/usr/local/lib/python3.6/site-packages/TCLIService/TCLIService.py", line 218, in CloseSession
return self.recv_CloseSession()
File "/usr/local/lib/python3.6/site-packages/TCLIService/TCLIService.py", line 230, in recv_CloseSession
(fname, mtype, rseqid) = iprot.readMessageBegin()
File "/usr/local/lib/python3.6/site-packages/thrift/protocol/TBinaryProtocol.py", line 134, in readMessageBegin
sz = self.readI32()
File "/usr/local/lib/python3.6/site-packages/thrift/protocol/TBinaryProtocol.py", line 217, in readI32
buff = self.trans.readAll(4)
File "/usr/local/lib/python3.6/site-packages/thrift/transport/TTransport.py", line 60, in readAll
chunk = self.read(sz - have)
File "/usr/local/lib/python3.6/site-packages/thrift_sasl/__init__.py", line 166, in read
self._read_frame()
File "/usr/local/lib/python3.6/site-packages/thrift_sasl/__init__.py", line 170, in _read_frame
header = self._trans.readAll(4)
File "/usr/local/lib/python3.6/site-packages/thrift/transport/TTransport.py", line 60, in readAll
chunk = self.read(sz - have)
File "/usr/local/lib/python3.6/site-packages/thrift/transport/TSocket.py", line 117, in read
buff = self.handle.recv(sz)
TimeoutError: [Errno 110] Connection timed out
```

**Comment by shurik2533** [comment]
This workaround with retries may help:
```python
from urllib import parse

from pyhive import presto
from requests import Session
from requests.adapters import HTTPAdapter
from urllib3.util.retry import Retry


class Presto:
    def __init__(self, host, port, username=None, password=None, rewrite_url=None, retries=(1, 5)):
        self.host = host
        self.port = port
        self.username = username
        self.password = password

        self.rewrite_url = rewrite_url
        self.engine = 'PRESTO'

        try:
            self.retries = retries[0]
            self.retries_backoff = retries[1]
        except TypeError:
            self.retries = retries
            self.retries_backoff = 5

    def connect(self):
        credentials = {'username': self.username, 'password': self.password}
        return presto.connect(
            self.host,
            self.port,
            protocol='https',
            requests_session=RetriablePrestoSession(
                host_rewrite=self.rewrite_url,
                connect=self.retries,
                backoff_factor=self.retries_backoff,
                auth=credentials,
                proxy_netloc='{}:{}'.format(self.host, self.port) if self.rewrite_url else None,
            ),
            **credentials
        )


class RetriablePrestoSession(Session):
    def __init__(self, host_rewrite=None, proxy_netloc=None, connect=5, backoff_factor=1, auth=None):
        Session.__init__(self)
        if host_rewrite:
            self.headers['Host'] = host_rewrite
        if auth:
            self.auth = (auth['username'], auth['password'])

        self.__proxy_netloc = proxy_netloc
        self.verify = False
        adapter = HTTPAdapter(max_retries=Retry(connect, backoff_factor))
        self.mount('http://', adapter)
        self.mount('https://', adapter)

    def _replace_host(self, url):
        if not self.__proxy_netloc:
            return url
        p = parse.urlparse(url)
        return parse.ParseResult(**dict(p._asdict(), netloc=self.__proxy_netloc)).geturl()

    def get(self, url, *args, **kwargs):
        return Session.get(self, self._replace_host(url), *args, **kwargs)

    def post(self, url, *args, **kwargs):
        return Session.post(self, self._replace_host(url), *args, **kwargs)

    def put(self, url, *args, **kwargs):
        return Session.put(self, self._replace_host(url), *args, **kwargs)

    def delete(self, url, *args, **kwargs):
        return Session.delete(self, self._replace_host(url), *args, **kwargs)
```
