### ISSUE TITLE
hive LDAP with SSL not working

### ISSUE THREAD

**Issue by Gaurang033** [dropbox/PyHive#257]
hi Guys, 

I have two environment,  Dev and PROD.  In Dev we don't have SSL enabled for LDAP and so I am able to connect and run query. 

However in PROD we have LDAP with SSL and whenever I tried to connect it gives me error. 
**packages**
```
sasl==0.2.1
thrift==0.11.0
thrift-sasl==0.3.0
PyHive==0.6.1
``` 
**Code:**
```
hive.connect(host='Host',
	         port=10000,
	         database='default',
	         username='gaurang.shah',
	         password="MyPassword",
	         auth='LDAP')
```
Following is part of the configuration. 

```
<property>
	<name>hive.server2.transport.mode</name>
	<value>binary</value>
</property>

<property>
	<name>hive.server2.use.SSL</name>
	<value>true</value>
</property>
```

Following is the **stacktrace**: 

```
Traceback (most recent call last):
  File "/Users/gaurang.shah/Documents/ctc/code/emsr/libs/hive.py", line 63, in <module>
    Hive().connect()
  File "/Users/gaurang.shah/Documents/ctc/code/emsr/libs/hive.py", line 45, in connect
    auth='LDAP'
  File "/Users/gaurang.shah/Documents/personal/code/migration/.venv/lib/python2.7/site-packages/pyhive/hive.py", line 94, in connect
    return Connection(*args, **kwargs)
  File "/Users/gaurang.shah/Documents/personal/code/migration/.venv/lib/python2.7/site-packages/pyhive/hive.py", line 192, in __init__
    self._transport.open()
  File "/Users/gaurang.shah/Documents/personal/code/migration/.venv/lib/python2.7/site-packages/thrift_sasl/__init__.py", line 87, in open
    status, payload = self._recv_sasl_message()
  File "/Users/gaurang.shah/Documents/personal/code/migration/.venv/lib/python2.7/site-packages/thrift_sasl/__init__.py", line 108, in _recv_sasl_message
    payload = self._trans.readAll(length)
  File "/Users/gaurang.shah/Documents/personal/code/migration/.venv/lib/python2.7/site-packages/thrift/transport/TTransport.py", line 60, in readAll
    chunk = self.read(sz - have)
  File "/Users/gaurang.shah/Documents/personal/code/migration/.venv/lib/python2.7/site-packages/thrift/transport/TSocket.py", line 132, in read
    message='TSocket read 0 bytes')
thrift.transport.TTransport.TTransportException: TSocket read 0 bytes
```

**Comment by devinstevenson** [comment]
hi @Gaurang033. pyhive does not support SSL sockets. I have a basic implementation to support SSL. Please give it a try. https://github.com/devinstevenson/pure-transport. Happy to get any feedback.

**Comment by tooptoop4** [comment]
@devinstevenson - PyHive does not support SSL? seems this would mean its no-go for enterprise

**Comment by devinstevenson** [comment]
@tooptoop4 The hive connection of PyHive does not use SSL by default, however the presto connection uses https by default. But PyHive does support users providing their own transport mechanism, which one can implement SSL. My library https://github.com/devinstevenson/pure-transport, helps facilitate the implementation.

**Comment by sujeeth62** [comment]
@devinstevenson - I am trying to run one of your sample example. Getting below error:
`Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "C:\Users\hingsuja\envs\py35\lib\site-packages\pyhive\hive.py", line 94, in connect
    return Connection(*args, **kwargs)
  File "C:\Users\hingsuja\envs\py35\lib\site-packages\pyhive\hive.py", line 192, in __init__
    self._transport.open()
  File "C:\Users\hingsuja\envs\py35\lib\site-packages\thrift_sasl\__init__.py", line 82, in open
    self._send_message(self.START, chosen_mech)
  File "C:\Users\hingsuja\envs\py35\lib\site-packages\thrift_sasl\__init__.py", line 101, in _send_message
    self._trans.write(header + body)
TypeError: can't concat bytes to str`

Please can you help he with the same.

**Comment by sujeeth62** [comment]
Hi All,
Add below code snippet at "C:\Users\hingsuja\envs\py35\lib\site-packages\thrift_sasl\__init__.py", line 101, in _send_message:
```
if (type(body) is str):
  body = body.encode() 

```

**Comment by anderl80** [comment]
@devinstevenson unfortunately your package does not work and throw an error. I opened a ticket on your github repository.

**Comment by malavshah1** [comment]
seems this is overwriting transport on pyhive and removing requirements for certificate? Is this correct? How this works without certificate on client side?
