### ISSUE TITLE
PyHive don't connect - Kerberized Cluster

### ISSUE THREAD

**Issue by sardano** [dropbox/PyHive#267]
Hi my name is Sardano, I’m from Brazil.

Please can you help me?

I looking for a solution on internet, but at to the moment without success.
Please, if I staing in the wrong place to get support for PyHive, let know the right place.

I try to connect in our Hiveserver2 (Hortownworks Kerberized Cluster), but without success, geting the message:

Python 2.7.15 |Anaconda, Inc.| (default, Dec 14 2018, 19:04:19)
[GCC 7.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from pyhive import hive
>>> c=hive.Connection(host='clusterKerberizado', port='2181', auth='KERBEROS', kerberos_service_name='krbtgt', configuration={'serviceDiscoveryMode':'zooKeeper','zooKeeperNamespace':'hiveserver2'})
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/papaleguas/miniconda/lib/python2.7/site-packages/pyhive/hive.py", line 192, in __init__
    self._transport.open()
  File "/home/papaleguas/miniconda/lib/python2.7/site-packages/thrift_sasl/__init__.py", line 79, in open
    message=("Could not start SASL: %s" % self.sasl.getError()))
thrift.transport.TTransport.TTransportException: Could not start SASL: Error in sasl_client_start (-4) SASL(-4): no mechanism available: No worthy mechs found

These are my configurations:

$ rpm -qa | grep -i "cyrus"
cyrus-sasl-gssapi-2.1.26-21.el7.x86_64
cyrus-sasl-plain-2.1.26-21.el7.x86_64
cyrus-sasl-lib-2.1.26-21.el7.x86_64

$ conda list
# packages in environment at /home/sardano/miniconda:            
#                                                                
# Name                    Version                   Build  Channel
asn1crypto                0.24.0                   py27_0         
atk                       1.28.0                        0    ska  
bcrypt                    3.1.6            py27h7b6447c_0         
bumpversion               0.5.3                   py_1001    conda-forge
bzip2                     1.0.6                h14c3975_5               
ca-certificates           2019.1.23                     0               
cairo                     1.8.8                         0    ska        
certifi                   2018.11.29               py27_0               
cffi                      1.11.5           py27he75722e_1               
chardet                   3.0.4                    py27_1               
click                     7.0                      py27_0               
conda                     4.6.2                    py27_0               
conda-env                 2.6.0                         1               
cryptography              2.4.2            py27h1ba5d50_0               
cx_oracle                 7.0.0            py27h7b6447c_0               
cyrus-sasl                2.1.26               h82bf5a1_4               
django                    1.11.10          py27hd476221_0               
django-cachalot           2.1.0                      py_0    conda-forge
django-environ            0.4.5                      py_1    conda-forge
django-guardian           1.5.0                      py_0    conda-forge
djangorestframework       3.9.1                      py_0    conda-forge
enum34                    1.1.6                    py27_1               
expat                     2.1.0                    py27_0    ska        
flask                     1.0.2                    py27_1               
fontconfig                2.7.3                         0    ska        
funcsigs                  1.0.2                      py_3    conda-forge
future                    0.17.1                   py27_0               
futures                   3.2.0                    py27_0               
gevent                    1.4.0            py27h7b6447c_0               
glib                      2.22.2                        0    ska        
greenlet                  0.4.15           py27h7b6447c_0               
gtk-plus                  2.18.3                        0    ska        
happybase                 1.1.0                    py27_2    conda-forge
hdfs3                     0.3.0                    py27_1               
icu                       58.2                 h9c2bf20_1               
idna                      2.8                      py27_0               
ipaddress                 1.0.22                   py27_0               
itsdangerous              1.1.0                    py27_0               
jinja2                    2.10                     py27_0               
kazoo                     2.2.1                    py27_0    activisiongamescience
krb5                      1.16.1               h173b8e3_7                         
libboost                  1.67.0               h46d08c1_4                         
libcurl                   7.63.0            h20c2e04_1000                         
libdb                     6.1.26               he6710b0_0                         
libedit                   3.1.20170329         h6b74fdf_2                         
libffi                    3.2.1                hd88cf55_4                         
libgcc-ng                 8.2.0                hdf63c60_1                         
libgcrypt                 1.8.4                h7b6447c_0                         
libgpg-error              1.32                 hf484d3e_0                         
libgsasl                  1.8.0                h7b6447c_3                         
libhdfs3                  2.3.0                h2fca0e8_1                         
libntlm                   1.4                  h14c3975_2                         
libpq                     11.1                 h20c2e04_0                         
libprotobuf               3.6.0                hdbcaa40_0                         
libsodium                 1.0.16               h1bed415_0                         
libssh2                   1.8.0                h1ba5d50_4                         
libstdcxx-ng              8.2.0                hdf63c60_1                         
libuuid                   1.0.3                h1bed415_2                         
libxml2                   2.9.9                he19cac6_0                         
markupsafe                1.1.0            py27h7b6447c_0                         
mock                      2.0.0                 py27_1000    conda-forge          
mysql-connector-c         6.1.11               h597af5e_0                         
mysql-connector-python    8.0.13           py27h9c95fcb_0                         
ncurses                   6.1                  he6710b0_1                         
openssl                   1.1.1a               h7b6447c_0                         
pango                     1.26.0                        0    ska                  
paramiko                  2.4.2                    py27_0                         
pbr                       5.1.2                      py_0    conda-forge          
pip                       18.1                     py27_0                         
pixman                    0.16.2                        0    ska                  
ply                       3.11                       py_1    conda-forge          
protobuf                  3.6.0            py27hf484d3e_0                         
psycopg2                  2.7.6.1          py27h1ba5d50_0                         
pyasn1                    0.4.5                      py_0                         
pycairo                   1.8.8                         0    ska                  
pycosat                   0.6.3            py27h14c3975_0                         
pycparser                 2.19                     py27_0
pydoop                    1.2.0                    pypi_0    pypi
pygobject                 2.20.0                        0    ska
pygtk                     2.16.0                        0    ska
pyhive                    0.6.1                    py27_0
pynacl                    1.3.0            py27h7b6447c_0
pyopenssl                 18.0.0                   py27_0
pysocks                   1.6.8                    py27_0
python                    2.7.15               h9bab390_6
pytz                      2018.9                   py27_0
readline                  7.0                  h7b6447c_5
requests                  2.21.0                   py27_0
ruamel_yaml               0.15.46          py27h14c3975_0
sasl                      0.2.1            py27h779454e_1
setuptools                40.6.3                   py27_0
simplejson                3.16.0           py27h14c3975_0
six                       1.12.0                   py27_0
sqlalchemy                1.2.16           py27h7b6447c_0
sqlite                    3.26.0               h7b6447c_0
thrift                    0.11.0           py27hf484d3e_0
thrift_sasl               0.3.0                    py27_1
thriftpy                  0.3.9           py27h14c3975_1001    conda-forge
tk                        8.6.8                hbc83047_0
urllib3                   1.24.1                   py27_0
werkzeug                  0.14.1                   py27_0
wheel                     0.32.3                   py27_0
xz                        5.2.4                h14c3975_4
yaml                      0.1.7                had09818_2
zlib                      1.2.11               h7b6447c_3

$ klist -e
Ticket cache: FILE:/tmp/krb5cc_ papaleguas
Default principal: papaleguas @THUNDER.BR

Valid starting       Expires              Service principal
02/15/2019 08:06:01  02/15/2019 18:06:01  krbtgt/ THUNDER.BR@ THUNDER.BR
        renew until 02/16/2019 08:05:53, Etype (skey, tkt): arcfour-hmac, arcfour-hmac

Thanks in advance and best regards,

Sardano

**Comment by sardano** [comment]
#!/usr/bin/env python

# Studying the PyHive code, I've isolated these small simplified snippy of code to reproduce the problem:

import thrift.transport.TSocket
import thrift.transport.TTransport
import sasl

host = ""
kerberos_service_name = ""

def sasl_factory():
    sasl_client = sasl.Client()
    sasl_client.setAttr('host', host)
    sasl_client.setAttr('service', kerberos_service_name)
    sasl_client.init()
    return sasl_client

# Copy of PyHive code (simplifyed):
def pyhive_simplified(port, sasl_auth):
    print "PyHive Simplified code ----------------------------------------------------"
    socket = thrift.transport.TSocket.TSocket(host, port)
    import thrift_sasl
    _transport = thrift_sasl.TSaslClientTransport(sasl_factory, sasl_auth, socket)
    socket.open()
    _transport.open()
    print "OK"

def sasl_simplified_code(port, sasl_auth):
    print "SASL Simplified Code ----------------------------------------------------"
    socket = thrift.transport.TSocket.TSocket(host, port)
    socket.open()
    sasl_x = sasl_factory()
    ret, chosen_mech, initial_response = sasl_x.start(sasl_auth)
    if not ret:
        print "Could not start SASL: %s" % sasl_x.getError()
    else:
        print "OK"
    socket.close()

if __name__ == "__main__":
    host = 'clusterKerberizado'
    port = '2181'
    kerberos_service_name = 'hive'
    sasl_auth = 'GSSAPI' # KERBEROS
    try:
        pyhive_simplified(port, sasl_auth)
    except Exception as e:
        print str(e)
    sasl_simplified_code(port, sasl_auth)

-------------------------------------
result:
-------------------------------------
$ ./t.py
PyHive Simplified code ----------------------------------------------------
Could not start SASL: Error in sasl_client_start (-4) SASL(-4): no mechanism available: No worthy mechs found
SASL Simplified Code ----------------------------------------------------
Could not start SASL: Error in sasl_client_start (-4) SASL(-4): no mechanism available: No worthy mechs found

**Comment by bond-** [comment]
I am running into a similar error.

> thrift.transport.TTransport.TTransportException: Could not start SASL: b'Error in sasl_client_start (-1) SASL(-1): generic failure: GSSAPI Error: Unspecified GSS failure.  Minor code may provide more information (Server not found in Kerberos database)'

**Comment by kz33** [comment]
I had the same problem, then I run the following command, it works for me.
```
yum install -y  cyrus-sasl-plain \
                   cyrus-sasl-devel \
                   cyrus-sasl-gssapi \
                   cyrus-sasl-md5 
```

**Comment by sardano** [comment]
Thanks for the answer Jiekun!

Best regards,

Sardano


⁣Enviado por BlueMail ​

Em 22 de set de 2020 13:05, em 13:05, Jiekun Zhang <notifications@github.com> escreveu:
