### ISSUE TITLE
TTransportException: Negative length: -407722777

### ISSUE THREAD

**Issue by dacoolbaby** [dropbox/PyHive#322]
Traceback (most recent call last):
  File "pyhive_prd_demo.py", line 23, in <module>
    print(cur.fetchall())
  File "/usr/local/python3/lib/python3.7/site-packages/pyhive/common.py", line 136, in fetchall
    return list(iter(self.fetchone, None))
  File "/usr/local/python3/lib/python3.7/site-packages/pyhive/common.py", line 105, in fetchone
    self._fetch_while(lambda: not self._data and self._state != self._STATE_FINISHED)
  File "/usr/local/python3/lib/python3.7/site-packages/pyhive/common.py", line 45, in _fetch_while
    self._fetch_more()
  File "/usr/local/python3/lib/python3.7/site-packages/pyhive/hive.py", line 386, in _fetch_more
    response = self._connection.client.FetchResults(req)
  File "/usr/local/python3/lib/python3.7/site-packages/TCLIService/TCLIService.py", line 714, in FetchResults
    return self.recv_FetchResults()
  File "/usr/local/python3/lib/python3.7/site-packages/TCLIService/TCLIService.py", line 733, in recv_FetchResults
    result.read(iprot)
  File "/usr/local/python3/lib/python3.7/site-packages/TCLIService/TCLIService.py", line 3470, in read
    self.success.read(iprot)
  File "/usr/local/python3/lib/python3.7/site-packages/TCLIService/ttypes.py", line 6583, in read
    self.results.read(iprot)
  File "/usr/local/python3/lib/python3.7/site-packages/TCLIService/ttypes.py", line 2867, in read
    _elem115.read(iprot)
  File "/usr/local/python3/lib/python3.7/site-packages/TCLIService/ttypes.py", line 2741, in read
    self.stringVal.read(iprot)
  File "/usr/local/python3/lib/python3.7/site-packages/TCLIService/ttypes.py", line 2521, in read
    _elem95 = iprot.readString().decode('utf-8') if sys.version_info[0] == 2 else iprot.readString()
  File "/usr/local/python3/lib/python3.7/site-packages/thrift/protocol/TProtocol.py", line 185, in readString
    return binary_to_str(self.readBinary())
  File "/usr/local/python3/lib/python3.7/site-packages/thrift/protocol/TBinaryProtocol.py", line 233, in readBinary
    self._check_string_length(size)
  File "/usr/local/python3/lib/python3.7/site-packages/thrift/protocol/TBinaryProtocol.py", line 47, in _check_string_length
    self._check_length(self.string_length_limit, length)
  File "/usr/local/python3/lib/python3.7/site-packages/thrift/protocol/TProtocol.py", line 59, in _check_length
    'Negative length: %d' % length)
thrift.transport.TTransport.TTransportException: Negative length: -407722777

**Comment by Lordshinjo** [comment]
`thrift-sasl==0.4.2` was released yesterday including https://github.com/cloudera/thrift_sasl/pull/23, which should fix this.
