### ISSUE TITLE
PyHive Presto failing intermittently with "Remote end closed connection without response" error

### ISSUE THREAD

**Issue by brettplarson** [dropbox/PyHive#329]
Hello,
I am running into an issue and have been struggling with this for several weeks.
We are using PyHive to poll presto but intermittently we run into this error.

Here is the code:
```
cursor = presto.connect( url, port=8380, schema="default",
                        catalog="hive", protocol="https", username=user, password=token,
                        requests_session=session,
                        requests_kwargs={'verify': False}).cursor()
```
Here is the exception:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 672, in urlopen
    chunked=chunked,
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 421, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 416, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.5/http/client.py", line 1213, in getresponse
    response.begin()
  File "/usr/lib/python3.5/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.5/http/client.py", line 276, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 720, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/usr/local/lib/python3.5/dist-packages/urllib3/util/retry.py", line 400, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python3.5/dist-packages/urllib3/packages/six.py", line 734, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 672, in urlopen
    chunked=chunked,
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 421, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 416, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.5/http/client.py", line 1213, in getresponse
    response.begin()
  File "/usr/lib/python3.5/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.5/http/client.py", line 276, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
```

From what I understand this is due to the remote end closing the connection.

Is there any other parameter I should be setting to control timeout for this connect or to retry the connection?

I understand that this is probably not an issue with the PyHive code, but I'm looking for any assistance as i'm out of ideas.
Thank you in advance.

**Comment by brettplarson** [comment]
Hello,
This issue was caused by [A reason for unexplained connection timeouts on Kubernetes/Docker](https://tech.xing.com/a-reason-for-unexplained-connection-timeouts-on-kubernetes-docker-abd041cf7e02) and was unrelated to PyHive.

**Comment by kamalrajs86** [comment]
@brettplarson : I got the same issue "Remote end closed connection without response" in Production. Here my client is EC2 VM and server is Presto cluster. I have batch job which runs 3 hours. Sometimes 45 minutes elapsed time query runs fine, and sometimes 10 mins fails. Really out of idea, how to solve this issue.  Your help is really appreciated.
