### ISSUE TITLE
can't pip install

### ISSUE THREAD

**Issue by austintrombley** [dropbox/PyHive#57]
I can't pip install pyhive on a windws box:

C:\Users\atrombley>pip install pyhive
Downloading/unpacking pyhive
  Running setup.py (path:c:\users\atromb~1\appdata\local\temp\2\pip_build_atromb
ley\pyhive\setup.py) egg_info for package pyhive

Downloading/unpacking future (from pyhive)
  Running setup.py (path:c:\users\atromb~1\appdata\local\temp\2\pip_build_atromb
ley\future\setup.py) egg_info for package future

    warning: no files found matching '*.au' under directory 'tests'
    warning: no files found matching '*.gif' under directory 'tests'
    warning: no files found matching '*.txt' under directory 'tests'
Installing collected packages: pyhive, future
  Running setup.py install for pyhive

  Could not find .egg-info directory in install record for pyhive
Cleaning up...
Exception:
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\pip\basecommand.py", line 122, in main
    status = self.run(options, args)
  File "C:\Python27\lib\site-packages\pip\commands\install.py", line 283, in run

    requirement_set.install(install_options, global_options, root=options.root_p
ath)
  File "C:\Python27\lib\site-packages\pip\req.py", line 1435, in install
    requirement.install(install_options, global_options, *args, **kwargs)
  File "C:\Python27\lib\site-packages\pip\req.py", line 749, in install
    os.remove(record_filename)
WindowsError: [Error 32] The process cannot access the file because it is being
used by another process: 'c:\\users\\atromb~1\\appdata\\local\\temp\\2\\pip-ndmn
vn-record\\install-record.txt'

Storing debug log for failure in C:\Users\atrombley\pip\pip.log

**Comment by jingw** [comment]
Sorry, I have no idea about Windows. (I use exclusively Linux)

I'll leave this open in case some passerby can chime in.

**Comment by zruu** [comment]
I think this is not related to PyHive or Windows itself. I get this error on my Debian 8 server when trying to install multiple applications. It could be some dependancy issue.

**Comment by devinstevenson** [comment]
see my PR https://github.com/dropbox/PyHive/pull/122 to install on Windows. for dependencies make sure to use the --no-deps flag with pip. Also requires pure-sasl.

# Dependencies
```
# for Presto
requests

# for Hive
thrift>=0.10.0
thrift_sasl>=0.2.1
pure-sasl>=0.3.0
```

```
> pip install thrift --no-deps
> pip install thrift_sasl --no-deps
> pip install pure-sasl
```

To install pyhive, clone repo and change to branch `feature-pure-sasl-win`. In repo folder run 
```
> python setup.py sdist
> cd dist
> pip install PyHive-0.3.0.dev0.tar.gz
```

**Comment by opticalix** [comment]
@devinstevenson Can't find any branch named feature-pure-sasl-win..
