### ISSUE TITLE
Is Hive "CREATE TABLE" execution working ?

### ISSUE THREAD

**Issue by jbarotin** [dropbox/PyHive#60]
I'm trying the following code  :
```
from pyhive import hive
cursor = hive.connect(ip).cursor()
cursor.execute(""""CREATE TABLE test_create_pyhive_1 ( a INT)""")
```

It gives me this kind of error : 
````ParseException line 1:43 character '<EOF>' not supported here````

You can find the full trace here :
```
Traceback (most recent call last):
  File "/home/jerome/test/manual/test_pyhive_create_table.py", line 13, in <module>
    cursor.execute(""""CREATE TABLE test_create_pyhive_1 ( a INT)""")
  File "/home/jerome/virtenv/lib/python2.7/site-packages/pyhive/hive.py", line 240, in execute
    _check_status(response)
  File "/home/jerome/virtenv/lib/python2.7/site-packages/pyhive/hive.py", line 362, in _check_status
    raise OperationalError(response)
pyhive.exc.OperationalError: TExecuteStatementResp(status=TStatus(errorCode=40000, errorMessage="Error while compiling statement: FAILED: ParseException line 1:43 character '<EOF>' not supported here", sqlState='42000', infoMessages=
["*org.apache.hive.service.cli.HiveSQLException:Error while compiling statement: FAILED: ParseException line 1:43 character '<EOF>' not supported here:28:27", 'org.apache.hive.service.cli.operation.Operation:toSQLException:Operation.java:374', 'org.apache.hive.service.cli.operation.SQLOperation:prepare:SQLOperation.java:136', 'org.apache.hive.service.cli.operation.SQLOperation:runInternal:SQLOperation.java:206', 'org.apache.hive.service.cli.operation.Operation:run:Operation.java:316', 'org.apache.hive.service.cli.session.HiveSessionImpl:executeStatementInternal:HiveSessionImpl.java:425', 'org.apache.hive.service.cli.session.HiveSessionImpl:executeStatement:HiveSessionImpl.java:395', 'sun.reflect.GeneratedMethodAccessor44:invoke::-1', 'sun.reflect.DelegatingMethodAccessorImpl:invoke:DelegatingMethodAccessorImpl.java:43', 'java.lang.reflect.Method:invoke:Method.java:606', 'org.apache.hive.service.cli.session.HiveSessionProxy:invoke:HiveSessionProxy.java:78', 'org.apache.hive.service.cli.session.HiveSessionProxy:access$000:HiveSessionProxy.java:36', 'org.apache.hive.service.cli.session.HiveSessionProxy$1:run:HiveSessionProxy.java:63', 'java.security.AccessController:doPrivileged:AccessController.java:-2', 'javax.security.auth.Subject:doAs:Subject.java:415', 'org.apache.hadoop.security.UserGroupInformation:doAs:UserGroupInformation.java:1693', 'org.apache.hive.service.cli.session.HiveSessionProxy:invoke:HiveSessionProxy.java:59', 'com.sun.proxy.$Proxy25:executeStatement::-1', 'org.apache.hive.service.cli.CLIService:executeStatement:CLIService.java:245', 'org.apache.hive.service.cli.thrift.ThriftCLIService:ExecuteStatement:ThriftCLIService.java:506', 'org.apache.hive.service.cli.thrift.TCLIService$Processor$ExecuteStatement:getResult:TCLIService.java:1313', 'org.apache.hive.service.cli.thrift.TCLIService$Processor$ExecuteStatement:getResult:TCLIService.java:1298', 'org.apache.thrift.ProcessFunction:process:ProcessFunction.java:39', 'org.apache.thrift.TBaseProcessor:process:TBaseProcessor.java:39', 'org.apache.hive.service.auth.TSetIpAddressProcessor:process:TSetIpAddressProcessor.java:56', 'org.apache.thrift.server.TThreadPoolServer$WorkerProcess:run:TThreadPoolServer.java:285', 'java.util.concurrent.ThreadPoolExecutor:runWorker:ThreadPoolExecutor.java:1145', 'java.util.concurrent.ThreadPoolExecutor$Worker:run:ThreadPoolExecutor.java:615', 'java.lang.Thread:run:Thread.java:745', "*org.apache.hadoop.hive.ql.parse.ParseException:line 1:43 character '<EOF>' not supported here:33:6", 'org.apache.hadoop.hive.ql.parse.ParseDriver:parse:ParseDriver.java:210', 'org.apache.hadoop.hive.ql.parse.ParseDriver:parse:ParseDriver.java:166', 'org.apache.hadoop.hive.ql.Driver:compile:Driver.java:423', 'org.apache.hadoop.hive.ql.Driver:compile:Driver.java:311', 'org.apache.hadoop.hive.ql.Driver:compileInternal:Driver.java:1194', 'org.apache.hadoop.hive.ql.Driver:compileAndRespond:Driver.java:1181', 'org.apache.hive.service.cli.operation.SQLOperation:prepare:SQLOperation.java:134'], statusCode=3), operationHandle=None)
```

I saw in the code, that in the tests "create table" is executed from hive shell. So, my question is, "is it possible to create table with pyhive ?"

**Comment by jbarotin** [comment]
that's strange the following code is working : 

```
from pyhive import hive

cursor = hive.connect(ip).cursor()

cursor.execute("CREATE TABLE test_create_pyhive_1 ( a INT)")
```

In fact, my problem come from """ string in order of " string.

**Comment by jbarotin** [comment]
Find this https://stackoverflow.com/questions/31439715/python-syntaxerror-eof-while-scanning-triple-quoted-string-literal anwer fixed my issue, you can find the code below: 

```

from pyhive import hive

cursor = hive.connect(ip).cursor()

cursor.execute(b"""CREATE TABLE test_create_pyhive_1 ( a INT)""")
```

**Comment by mschmill** [comment]
The OP has 4 quotes to start the string.

**Comment by jbarotin** [comment]
Ooops, and it works thanks a lot.
