### ISSUE TITLE
There have a synatx error when import hive model after install pyhive.

### ISSUE THREAD

**Issue by elkan1788** [dropbox/PyHive#74]
Hi, man. I had install Pyhive on my server. Also there out put the success log:

```
Installing collected packages: thrift-sasl, pyhive
  Running setup.py install for thrift-sasl ... done
  Running setup.py install for pyhive ... done
Successfully installed pyhive-0.2.1 thrift-sasl-0.2.1
```

But when I try to test import, there said `SyntaxError: invalid syntax`. The detail info see below:

```
Python 2.6.6 (r266:84292, Jul 23 2015, 15:22:56) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-11)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from pyhive import hive
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.6/site-packages/pyhive/hive.py", line 13, in <module>
    from pyhive import common
  File "/usr/lib/python2.6/site-packages/pyhive/common.py", line 219
    return {k: self.escape_item(v) for k, v in parameters.items()}
                                     ^
```

So is there any wrong operation in my step?  Thanks.

**Comment by jingw** [comment]
You need Python 2.7. Python 2.6 has been EOL for several years.

**Comment by elkan1788** [comment]
OK, Thanks.
