### ISSUE TITLE
Connect with a password or with NOSASL

### ISSUE THREAD

**Issue by moskalyk** [dropbox/PyHive#89]
I have a remote server that is using the hortonworks sandbox, and I'm trying to connect to the Hive db in that environment.

Is there a way to connect to a remote db with a password? I'm not using a password in this scenario, and it looks something like this:

```
from pyhive import hive

conn = hive.Connection(host="xx.xx.xx.xx", port=10000, username="username", auth='NOSASL', database='db')
```

and I get the following error

```
Traceback (most recent call last):
  File "connect.py", line 5, in <module>
    conn = hive.Connection(host="xx.xx.xx.xx", port=10000, username="username", auth='NOSASL', database='db')
  File "/Users/mmoskalyk/Projects/DataIngestionSolution/venv/lib/python3.5/site-packages/pyhive/hive.py", line 109, in __init__
    response = self._client.OpenSession(open_session_req)
  File "/Users/mmoskalyk/Projects/DataIngestionSolution/venv/lib/python3.5/site-packages/TCLIService/TCLIService.py", line 167, in OpenSession
    self.send_OpenSession(req)
  File "/Users/mmoskalyk/Projects/DataIngestionSolution/venv/lib/python3.5/site-packages/TCLIService/TCLIService.py", line 171, in send_OpenSession
    self._oprot.writeMessageBegin('OpenSession', TMessageType.CALL, self._seqid)
  File "/Users/mmoskalyk/Projects/DataIngestionSolution/venv/lib/python3.5/site-packages/thrift/protocol/TBinaryProtocol.py", line 46, in writeMessageBegin
    self.writeI32(TBinaryProtocol.VERSION_1 | type)
  File "/Users/mmoskalyk/Projects/DataIngestionSolution/venv/lib/python3.5/site-packages/thrift/protocol/TBinaryProtocol.py", line 111, in writeI32
    self.trans.write(buff)
  File "/Users/mmoskalyk/Projects/DataIngestionSolution/venv/lib/python3.5/site-packages/thrift/transport/TTransport.py", line 168, in write
    raise e
  File "/Users/mmoskalyk/Projects/DataIngestionSolution/venv/lib/python3.5/site-packages/thrift/transport/TTransport.py", line 164, in write
    self.__wbuf.write(buf)
TypeError: string argument expected, got 'bytes'
```

**Comment by jingw** [comment]
Sorry, password auth and python 3 support aren't currently implemented :(

**Comment by devinstevenson** [comment]
@moskalyk Password support is now available for LDAP authentication on the master branch

**Comment by mtdeguzis** [comment]
@devinstevenson this does not work for me, detailed under https://github.com/dropbox/PyHive/issues/143. Looking for some guidance.
